### ISSUE TITLE
Build fail - slow_tests (9914695637)

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#385]
https://github.com/cryptokaizen/orange/actions/runs/5449937493/jobs/9914695637
https://github.com/cryptokaizen/orange/actions/runs/5449491898/jobs/9913764031

Combining slow and superslow test failures in 1 issue since most of them are related and have same error
(note that a couple of tests failed due to the timeout)

Seems like a [portfolio refactoring ]( https://github.com/cryptokaizen/cmamp/pull/4714)that was merged necessitates a config change
Should be an easy orange/lemonade config follow-up

Assigning @PomazkinG to take a look and re-route if needed

Failed tests:
```
FAILED dataflow_orange/system/C1/test/test_C1b_forecast_system.py::Test_C1b_NonTime_ForecastSystem_FitPredict::test_fit_over_backtest_period1
FAILED dataflow_orange/system/C1/test/test_C1b_forecast_system.py::Test_C1b_NonTime_ForecastSystem_FitPredict::test_fit_over_period1
FAILED dataflow_orange/system/C1/test/test_C1b_forecast_system.py::Test_C1b_NonTime_ForecastSystem_CheckPnl::test_test_fit_run1
FAILED dataflow_orange/system/C1/test/test_C1b_forecast_system.py::Test_C1b_Time_ForecastSystem_with_DataFramePortfolio::test1
FAILED dataflow_orange/system/C1/test/test_C1b_forecast_system.py::Test_C1b_Time_ForecastSystem_with_DatabasePortfolio_and_OrderProcessor1::test1
FAILED dataflow_orange/system/C1/test/test_C1b_forecast_system.py::Test_C1b_Time_ForecastSystem_with_DatabasePortfolio_and_OrderProcessor_vs_DataFramePortfolio1::test1
FAILED dataflow_orange/system/C1/test/test_C1b_forecast_system.py::Test_C1b_Time_ForecastSystem_vs_Time_ForecastSystem_with_DataFramePortfolio1::test1
```

Logs example:
```
_ Test_C1b_Time_ForecastSystem_with_DatabasePortfolio_and_OrderProcessor_vs_DataFramePortfolio1.test1 _
Traceback (most recent call last):
  File "/app/dataflow_orange/system/C1/test/test_C1b_forecast_system.py", line 355, in test1
    self._test1(
  File "/app/amp/dataflow/system/system_test_case.py", line 971, in _test1
    actual = self._test_dataframe_portfolio_helper(
  File "/app/amp/dataflow/system/system_test_case.py", line 488, in _test_dataframe_portfolio_helper
    result_bundles = run_Time_ForecastSystem(
  File "/app/amp/dataflow/system/system_test_case.py", line 125, in run_Time_ForecastSystem
    dtfsysysig.check_SystemConfig(self, system, config_tag)
  File "/app/amp/dataflow/system/system_signature.py", line 334, in check_SystemConfig
    self.check_string(txt, tag=tag, purify_text=True, sort=sort)
  File "/app/amp/helpers/hunit_test.py", line 1441, in check_string
    is_equal = assert_equal(
  File "/app/amp/helpers/hunit_test.py", line 1012, in assert_equal
    diff_files(
  File "/app/amp/helpers/hunit_test.py", line 647, in diff_files
    raise RuntimeError(msg_as_str)
RuntimeError: 
--------------------------------------------------------------------------------
ACTUAL vs EXPECTED: Test_C1b_Time_ForecastSystem_with_DatabasePortfolio_and_OrderProcessor_vs_DataFramePortfolio1.test1
--------------------------------------------------------------------------------

######################################################################### (
system_config.dataframe_portfolio                                         (
######################################################################### (
dag_config:                                                               (
  resample:                                                               (
    in_col_groups: [('close',), ('volume',)]                              (
    out_col_group: ()                                                     (
    transformer_kwargs:                                                   (
      rule: 5T                                                            (
      resampling_groups: [({'close': 'close'}, 'last', {}), ({'close': 't (
      vwap_groups: [('close', 'volume', 'vwap')]                          (
    reindex_like_input: False                                             (
    join_output_with_input: False                                         (
  compute_ret_0:                                                          (
    in_col_groups: [('close',), ('vwap',), ('twap',)]                     (
    out_col_group: ()                                                     (
    transformer_kwargs:                                                   (
      mode: log_rets                                                      (
    col_mapping:                                                          (
      close: close.ret_0                                                  (
      vwap: vwap.ret_0                                                    (
      twap: twap.ret_0                                                    (
  compute_vol:                                                            (
    in_col_group: ('vwap.ret_0',)                                         (
    out_col_group: ('vwap.ret_0.vol',)                                    (
    drop_nans: True                                                       (
    permitted_exceptions: (<class 'ValueError'>,)                         (
  adjust_rets:                                                            (
    in_col_groups: [('vwap.ret_0',), ('vwap.ret_0.vol',)]                 (
    out_col_group: ()                                                     (
    transformer_kwargs:                                                   (
      term1_col: vwap.ret_0                                               (
      term2_col: vwap.ret_0.vol                                           (
      out_col: vwap.ret_0.vol_adj                                         (
      term2_delay: 2                                                      (
      operation: div                                                      (
    drop_nans: True                                                       (
  compress_rets:                                                          (
    in_col_groups: [('vwap.ret_0.vol_adj',)]                              (
    out_col_group: ()                                                     (
    col_mapping:                                                          (
      vwap.ret_0.vol_adj: vwap.ret_0.vol_adj.c                            (
  add_lags:                                                               (
    in_col_groups: [('vwap.ret_0.vol_adj.c',)]                            (
    out_col_group: ()                                                     (
    transformer_kwargs:                                                   (
      lag_delay: 0                                                        (
      num_lags: 4                                                         (
      first_lag: 0                                                        (
      separator: .                                                        (
    drop_nans: True                                                       (
  predict:                                                                (
    in_col_groups: [('vwap.ret_0.vol_adj.c.lag0',), ('vwap.ret_0.vol_adj. (
    out_col_group: ()                                                     (
    transformer_kwargs:                                                   (
      weights:                                                            (
        index=[vwap.ret_0.vol_adj.c.lag0, vwap.ret_0.vol_adj.c.lag3]      (
        columns=vwap.ret_0.vol_adj.shift_-2_hat                           (
        shape=(4, 1)                                                      (
                                   vwap.ret_0.vol_adj.shift_-2_hat        (
        vwap.ret_0.vol_adj.c.lag0                           -0.209        (
        vwap.ret_0.vol_adj.c.lag1                           -0.223        (
        vwap.ret_0.vol_adj.c.lag2                            0.304        (
        vwap.ret_0.vol_adj.c.lag3                           -0.264        (
      convert_to_dataframe: True                                          (
    drop_nans: True                                                       (
dag_builder_object: nid_prefix=                                           (
dag_builder_class: C1b_DagBuilder                                         (
system_class: Cx_Time_ForecastSystem_with_DataFramePortfolio              (
market_data_config:                                                       (
  file_path: s3://$CK_AWS_S3_BUCKET/unit_test/outcomes/Test_C1b_Time_Fore (
  aws_profile: ck                                                         (
  timestamp_db_column: end_datetime                                       (
  datetime_columns: ['start_datetime', 'end_datetime', 'timestamp_db']    (
  asset_id_col_name: asset_id                                             (
  replayed_delay_in_mins_or_timestamp: 2022-07-21 10:29:00-04:00          (
  delay_in_secs: 10                                                       (
  history_lookback: 4 days 00:00:00                                       (
  asset_ids: [1464553467]                                                 (
dag_runner_config:                                                        (
  bar_duration_in_secs: 300                                               (
  fit_at_beginning: False                                                 (
  rt_timeout_in_secs_or_time: 900                                         (
  max_distance_in_secs: 30                                                (
  wake_up_timestamp: None                                                 (
portfolio_config:                                                         (
  mark_to_market_col: close                                               (
  pricing_method: twap.5T                                                 (
  column_remap:                                                           (
    bid: bid                                                              (
    ask: ask                                                              (
    midpoint: midpoint                                                    (
    price: close                                                          (
research_forecast_evaluator_from_prices:                                  (
  style: cross_sectional                                                  (
  init:                                                                   (
    price_col: vwap                                                       (
    volatility_col: vwap.ret_0.vol                                        (
    prediction_col: vwap.ret_0.vol_adj.shift_-2_hat                       (
  kwargs:                                                                 (
    target_gmv: 100000.0                                                  (
    liquidate_at_end_of_day: False                                        (
    initialize_beginning_of_day_trades_to_zero: False                     (
process_forecasts_node_dict:                                              (
  prediction_col: vwap.ret_0.vol_adj.shift_-2_hat                         (
  volatility_col: vwap.ret_0.vol                                          (
  spread_col: None                                                        (
  portfolio:                                                              (
    <oms.portfolio.dataframe_portfolio.DataFramePortfolio at 0x>          |      <oms.portfolio.DataFramePortfolio at 0x>
      # holdings_shares=                                                  (
      Empty DataFrame                                                     (
      Columns: []                                                         (
      Index: []                                                           (
      # holdings_notional=                                                (
      Empty DataFrame                                                     (
      Columns: []                                                         (
      Index: []                                                           (
      # executed_trades_shares=                                           (
      Empty DataFrame                                                     (
      Columns: []                                                         (
      Index: []                                                           (
      # executed_trades_notional=                                         (
      Empty DataFrame                                                     (
      Columns: []                                                         (
      Index: []                                                           (
      # pnl=                                                              (
      Empty DataFrame                                                     (
      Columns: []                                                         (
      Index: []                                                           (
      # statistics=                                                       (
      Empty DataFrame                                                     (
      Columns: [pnl]                                                      (
      Index: []                                                           (
  process_forecasts_dict:                                                 (
    order_config:                                                         (
      order_type: price@twap                                              (
      passivity_factor: None                                              (
      order_duration_in_mins: 5                                           (
    optimizer_config:                                                     (
      backend: pomo                                                       (
      params:                                                             (
        style: cross_sectional                                            (
        kwargs:                                                           (
          bulk_frac_to_remove: 0.0                                        (
          bulk_fill_method: zero                                          (
          target_gmv: 100000.0                                            (
    execution_mode: real_time                                             (
    ath_start_time: None                                                  (
    trading_start_time: None                                              (
    ath_end_time: None                                                    (
    trading_end_time: None                                                (
    liquidate_at_trading_end_time: False                                  (
    share_quantization: no_quantization                                   (
event_loop_object: <_EventLoop running=False closed=False debug=False>    (
market_object: ReplayedMarketData at 0x=(_asset_id_col=asset_id <str>, _a (
object.builder_function:                                                  (
  market_object: dataflow_amp.system.Cx.Cx_forecast_system._get_market_da (
  portfolio_object: dataflow_amp.system.Cx.Cx_forecast_system._get_portfo (
  dag_object: dataflow_amp.system.Cx.Cx_forecast_system._get_dag          (
  dag_runner_object: dataflow_amp.system.Cx.Cx_forecast_system._get_dag_r (
portfolio_object:                                                         (
  <oms.portfolio.dataframe_portfolio.DataFramePortfolio at 0x>            |    <oms.portfolio.DataFramePortfolio at 0x>
    # holdings_shares=                                                    (
    Empty DataFrame                                                       (
    Columns: []                                                           (
    Index: []                                                             (
    # holdings_notional=                                                  (
    Empty DataFrame                                                       (
    Columns: []                                                           (
    Index: []                                                             (
    # executed_trades_shares=                                             (
    Empty DataFrame                                                       (
    Columns: []                                                           (
    Index: []                                                             (
    # executed_trades_notional=                                           (
    Empty DataFrame                                                       (
    Columns: []                                                           (
    Index: []                                                             (
    # pnl=                                                                (
    Empty DataFrame                                                       (
    Columns: []                                                           (
    Index: []                                                             (
    # statistics=                                                         (
    Empty DataFrame                                                       (
    Columns: [pnl]                                                        (
    Index: []                                                             (
dag_object: DAG at 0x=(_nx_dag=DiGraph with 9 nodes and 8 edges <networkx (
dag_runner_object:                                                        (
  RealTimeDagRunner at 0x=(config= <core.config.config_.Config>, _column_ (
    _asset_id_col='asset_id' <str>                                        (
    _asset_ids='[1464553467]' <list>                                      (
    _start_time_col_name='start_datetime' <str>                           (
    _end_time_col_name='end_datetime' <str>                               (
    _columns='None' <NoneType>                                            (
    _sleep_in_secs='1.0' <float>                                          (
    _timezone='America/New_York' <str>                                    (
    _column_remap='None' <NoneType>                                       (
    _filter_data_mode='assert' <str>                                      (
    _max_iterations='120' <int>                                           (
    _df= <pandas.core.frame.DataFrame>                                    (
                     end_datetime    asset_id        full_symbol     open (
      0 2022-07-14 13:25:00+00:00  1464553467  binance::ETH_USDT  1082.72 (
      1 2022-07-14 13:26:00+00:00  1464553467  binance::ETH_USDT  1083.08 (
      2 2022-07-14 13:27:00+00:00  1464553467  binance::ETH_USDT  1082.39 (
      ...                                                                 (
      21597 2022-07-29 13:22:00+00:00  1464553467  binance::ETH_USDT  167 (
      21598 2022-07-29 13:23:00+00:00  1464553467  binance::ETH_USDT  167 (
      21599 2022-07-29 13:24:00+00:00  1464553467  binance::ETH_USDT  167 (
    _knowledge_datetime_col_name='timestamp_db' <str>                     (
    _delay_in_secs='10' <int>>, 'bar_duration_in_secs': 300, 'rt_timeout_ (
Diff with:
> ./tmp_diff.sh
```

**Comment by DanilYachmenev** [comment]
Wrong repo, will re-file in the correct one
