### ISSUE TITLE
On-board Shaopeng (Bill) Zhu

### ISSUE THREAD

**Issue by jsmerix** [sorrentum/sorrentum#434]
Please follow this checklist. Post any errors you face in this issue.

- [ ] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/How_to_organize_your_work.md)
- [ ] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md). Read through the [first section](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md#supporting-os) if you are using Windows
- [ ] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md#sorrentum-dev-docker-container-aka-dev-container-cmamp-container) works
- [ ] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md) run successfully
- [ ] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md)
- [ ] Get assigned a warm-up issue
- [ ] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/General_rules_of_collaboration.md#morning-email)
- [ ] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- [ ] If you are graduating soon and you would like to get a part- / full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at gp@sorrentum.org
- [ ] Get up to speed in terms of the background knowledge for specific project
- For Web3 / Crypto : [README.md](https://github.com/sorrentum/sorrentum/blob/master/defi/README.md)
- For Arbitrage / Modeling: [From_zero_to_modeling.md](https://github.com/sorrentum/sorrentum/blob/master/docs/From_zero_to_modeling.md)
 
FYI @gpsaggese @samarth9008

**Comment by LibertasSpZ** [comment]
I installed Docker. "docker pull hello-world" runs as expected, but when I try to build the thin environment by running 

`> source dev_scripts/client_setup/build.sh
`
It does not find the file. I tried `find . dev_scripts/client_setup/build.sh` and `find . build.sh` inside my root folder, no such file.

Which directory do I cd to before running the `source ... /build.sh` command? Thanks.

**Comment by LibertasSpZ** [comment]
When I do `> source dev_scripts/client_setup/build.sh` I get `error:Getting requirements to build wheel did not run successfully. │ exit code: 1`. The `subprocess-exited-with-error` but the whole process hangs.

I opened another terminal to run `> source dev_scripts/setenv_amp.sh`. Got success message; the aliases are different. In particular we have `alias i='invoke' alias ih='invoke --help' ` etc.

But then when I do `i` followed by anything, such as  `i git_pull` or `i docker_bash`, I get "-bash: invoke: command not found". 

Please help with issues above. Thank you very much. @jsmerix

**Comment by jsmerix** [comment]
1. Can you run `> docker images | grep sorrentum` and post the output
2. Can you post longer (atleast last 30 relevant lines) stdout when you run `i docker_bash`

**Comment by LibertasSpZ** [comment]
1. Output after `docker images | grep sorrentum`: 
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

2. the full stdout when i run `i docker_bash`:
`INFO: > cmd='/usr/local/bin/invoke docker_bash'
## docker_bash: 
14:09:35 - INFO  lib_tasks_docker.py _docker_cmd:1252                   Pulling the latest version of Docker
## docker_pull: 
## docker_login: 
  ... 
  ... The config profile (ck) could not be found
  ... WARNING! Using --password via the CLI is insecure. Use --password-stdin.
  ... Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password
14:09:37 - ERROR hsystem.py _system:273             
################################################################################
cmd='(docker login -u AWS -p $(aws ecr get-login-password --profile ck) https://sorrentum) 2>&1' failed with rc='1'
################################################################################
Output of the failing command is:
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

The config profile (ck) could not be found
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Traceback (most recent call last):
  File "/usr/local/bin/invoke", line 8, in <module>
    sys.exit(program.run())
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/invoke/program.py", line 398, in run
    self.execute()
  File "/usr/local/lib/python3.11/site-packages/invoke/program.py", line 583, in execute
    executor.execute(*self.tasks)
  File "/usr/local/lib/python3.11/site-packages/invoke/executor.py", line 140, in execute
    result = call.task(*args, **call.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/invoke/tasks.py", line 138, in __call__
    result = self.body(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Libertas/src/sorrentum1/helpers/lib_tasks_docker.py", line 1288, in docker_bash
    _docker_cmd(ctx, docker_cmd_)
  File "/Users/Libertas/src/sorrentum1/helpers/lib_tasks_docker.py", line 1253, in _docker_cmd
    docker_pull(ctx)
  File "/usr/local/lib/python3.11/site-packages/invoke/tasks.py", line 138, in __call__
    result = self.body(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Libertas/src/sorrentum1/helpers/lib_tasks_docker.py", line 240, in docker_pull
    _docker_pull(ctx, base_image, stage, version)
  File "/Users/Libertas/src/sorrentum1/helpers/lib_tasks_docker.py", line 223, in _docker_pull
    docker_login(ctx)
  File "/usr/local/lib/python3.11/site-packages/invoke/tasks.py", line 138, in __call__
    result = self.body(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Libertas/src/sorrentum1/helpers/lib_tasks_docker.py", line 309, in docker_login
    hlitauti.run(ctx, cmd, use_system=True)
  File "/Users/Libertas/src/sorrentum1/helpers/lib_tasks_utils.py", line 226, in run
    res = hsystem.system(cmd, suppress_output=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Libertas/src/sorrentum1/helpers/hsystem.py", line 303, in system
    rc, _ = _system(
            ^^^^^^^^
  File "/Users/Libertas/src/sorrentum1/helpers/hsystem.py", line 277, in _system
    raise RuntimeError(
RuntimeError: cmd='(docker login -u AWS -p $(aws ecr get-login-password --profile ck) https://sorrentum) 2>&1' failed with rc='1'
truncated output=

The config profile (ck) could not be found
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password
`

**Comment by gpsaggese** [comment]
1) As to 2. I think it's the same error as https://github.com/sorrentum/sorrentum/issues/437#issuecomment-1646058893

2) Also `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?` is telling you that Docker is not running.
I suggest to go through some of the slides here https://github.com/sorrentum/sorrentum/blob/master/docs/README.md#technologies-used
to catch up with parts of the technology stack that you might not familiar with

3) In general @LibertasSpZ pls attach `txt` files than `docx` so they are easier to open.

@jsmerix we should apply the fix proposed by @sonaalKant until the problem is fixed upstream

**Comment by LibertasSpZ** [comment]
Thank you, @gpsaggese . I fixed the `source dev_scripts/client_setup/build.sh` issue as advised in #437  and got Docker running. Will heed your advise on reading the technology docs and using `txt` as attachments. 

I have another potential problem. After `i docker_bash` successfully creates a container, I want to stop that container with the possibility of restarting it. I followed the tutorial [here](https://github.com/sorrentum/sorrentum/blob/master/docs/README.md#technologies-used), but the behavior on my terminals are different. In particular when I do `docker stop [my_container_name]`, it exists with ERROR 137 (forced kill) and  `docker restart [same_container_name]` cannot resurrect it.

For full error msg please see the attachment 
[container_restart.txt](https://github.com/sorrentum/sorrentum/files/12140230/container_restart.txt)
. Note that same result appears when I use `-t 300` to allow 5 minutes of grace period before killing. Any idea if this is normal?

**Comment by LibertasSpZ** [comment]
Another potential bug/problem: running `i run_fast_tests`, it gets stuck at 23% [hangs > 5 min, which is confusing since timeout default is 5.0s from the test session `stdout`] with the following file: 

`im_v2/ccxt/data/client/test/test_ccxt_clients.py::TestCcxtPqByAssetClient1::test_read_data7 (0.31 s) PASSED [ 23%]
im_v2/ccxt/data/client/test/test_ccxt_clients.py::TestCcxtSqlRealTimeImClient1::test_get_end_ts_for_symbol1` 

 I re-ran with the option `i run_fast_tests --skip-submodules`; this time nothing gets stuck. The `Short Summary` section of the stdout (with `--skip-submodules`) is as attached here [test_hang.txt](https://github.com/sorrentum/sorrentum/files/12142281/test_hang.txt), where I don't find `im_v2/ccxt/data/client/test/test_ccxt_clients.py::TestCcxtSqlRealTimeImClient1::test_get_end_ts_for_symbol1` from `ERROR`, `SKIPPED` or `FAILED` so it must have been passed.

So it's possible that `im_v2/ccxt/data/client/test/test_ccxt_clients.py::TestCcxtSqlRealTimeImClient1::test_get_end_ts_for_symbol1` has a potential infinite loop depending on some internally generated random value, but I am not sure as I cannot access that file. 

*********

Assuming that the glitches above are not due to mistakes on my end, I am ready and excited for my warm-up issue. Thanks a lot!
@jsmerix @gpsaggese

**Comment by gpsaggese** [comment]
> Thank you, @gpsaggese . I fixed the `source dev_scripts/client_setup/build.sh` issue as advised in #437 and got Docker running. Will heed your advise on reading the technology docs and using `txt` as attachments.

Sg. Mastering the basic technologies pays 10x.

> I have another potential problem. After `i docker_bash` successfully creates a container, I want to stop that container with the possibility of restarting it. I followed the tutorial [here](https://github.com/sorrentum/sorrentum/blob/master/docs/README.md#technologies-used), but the behavior on my terminals are different. In particular when I do `docker stop [my_container_name]`, it exits with `ERROR 137` (forced kill) as opposed to `0`, and `docker restart [same_container_name]` cannot resurrect the container.
> 
> For full relevant msgs please see the attachment [container_restart.txt](https://github.com/sorrentum/sorrentum/files/12140230/container_restart.txt). Note that the same result happens when I use `docker stop -t 300 [my_container_name]` to allow 5 minutes of grace period before killing. Any idea if this is normal? Thanks a lot! @jsmerix @gpsaggese

I think `docker stop` sends SIGTERM / SIGKILL, which kills the container so it can't be restarted. I think you want to use `docker pause`. In any case, you can leave containers running. As the slides / book will explain, containers are not like VMs so you can leave them running without wasting CPU. I do it all the time.

**Comment by gpsaggese** [comment]
> Another potential bug/problem: running `i run_fast_tests`, it gets stuck at 23% [hangs > 5 min, which is confusing since timeout default is 5.0s] with the following file:
> 
> `im_v2/ccxt/data/client/test/test_ccxt_clients.py::TestCcxtSqlRealTimeImClient1::test_get_end_ts_for_symbol1`
> 
> I re-ran with the option `i run_fast_tests --skip-submodules`; this time nothing gets stuck. The `Short Summary` section of the `stdout` for the re-run is attached here [test_hang.txt](https://github.com/sorrentum/sorrentum/files/12142281/test_hang.txt), where I don't find `im_v2/ccxt/data/client/test/test_ccxt_clients.py::TestCcxtSqlRealTimeImClient1::test_get_end_ts_for_symbol1` from `ERROR`, `SKIPPED` or `FAILED` so it must have passed.
> 
> So it's possible that `im_v2/ccxt/data/client/test/test_ccxt_clients.py::TestCcxtSqlRealTimeImClient1::test_get_end_ts_for_symbol1` has a potential infinite loop depending on some internally generated random value, but I am not sure as I cannot access that file.
> 
> Assuming that the glitches above are not due to my mistakes, I am ready and excited for my warm-up issue. Thanks a lot! @jsmerix @gpsaggese

`TestCcxtSqlRealTimeImClient1` requires to run inside our VPN to connect to a DB. Since you are outside the VPN, the test hangs (which the timeout doesn't kick in is a different question... but it might be a bug in `pytest`).

You are definitively ready for the next task

**Comment by LibertasSpZ** [comment]
Thank you very much for your clarification, @gpsaggese ! Appreciated.
