### ISSUE TITLE
On-board Sonaal Kant

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#437]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#Important) 
  - [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/How_to_organize_your_work.md)
  - [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md)
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md#sorrentum-dev-docker-container-aka-dev-container-cmamp-container) works
  - [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md) run successfully
  - [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md)
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [x] Get assigned a warm-up issue
  - [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/documentation/general/general.md#morning-email)
  - [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
  - [ ] If you are graduating soon and you would like to get a full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at gp@sorrentum.org
 
FYI @gpsaggese @samarth9008

**Comment by samarth9008** [comment]
@DanilYachmenev The first link is not working.

**Comment by gpsaggese** [comment]
It seems to point to https://github.com/sorrentum/sorrentum/blob/master/README.md#important, which is correct. Maybe we should change `Important` to `Commitment to contribute`.

**Comment by DanilYachmenev** [comment]
> It seems to point to https://github.com/sorrentum/sorrentum/blob/master/README.md#important, which is correct. Maybe we should change `Important` to `Commitment to contribute`.

Oh it was broken actually
I've updated the link after the Samarth's call
Will be updated in the doc as well

**Comment by samarth9008** [comment]
I have updated that in my on-going PR.

**Comment by sonaalKant** [comment]
Hi, 

I am facing the installation issue after running this. Anybody know about this error, if not I will investigate.

```
source dev_scripts/client_setup/build.sh
```

```
Collecting PyYAML<6.1,>=3.10 (from awscli>=1.19->-r dev_scripts/client_setup/requirements.txt (line 1))
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      /private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/sonaal/src/venv/amp.client_venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/sonaal/src/venv/amp.client_venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/sonaal/src/venv/amp.client_venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in run
          self.find_sources()
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
          mm.run()
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/private/var/folders/2z/hg9dwmp51p17v6292h8jkl700000gn/T/pip-build-env-w254ej50/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

**Comment by sonaalKant** [comment]
Update : So awscli has a dependency on pyyaml, and latest pyyaml is not compatible with cython3 hence the bug.(This is still an open issue [[here](https://github.com/yaml/pyyaml/issues/601)] ) I fixed it by pinning the version of pyyaml ==.5.3.1. 

I made a change to ~/src/sorrentum1/dev_scripts/client_setup/requirements.txt

which now is 
```
pyyaml == 5.3.1 # Added this to support aws cli
awscli >= 1.19  # For aws CLI.
docker-compose >= 1.29.0
invoke >= 1.5.0
jupyter  # For publish_notebook
jupyter_contrib_nbextensions
pandas   # For publish_notebook
poetry
pytest >= "6.0.0"
pytest-cov
pytest-instafail
pytest-xdist
python-dateutil
s3fs  # For tools like `publish_notebook.py`.
tqdm
```

Let me know if something else needs to be done or this change can be pushed.

**Comment by gpsaggese** [comment]
Yeah, there was an article on HackerNews about this.

1) Good attitude in looking for a solution. That's what we like to see.
2) Let's give the maintainers some time to get their act in order, so we don't have to pin packages.

**Comment by sonaalKant** [comment]
Got it. Facing another issue while running docker_jupyter

Ran the following commands and got this.
 
```
user_501@29fc396c9563:/app$ i docker_jupyter
bash: i: command not found
```
```
user_501@29fc396c9563:/app$ invoke docker_jupyter

<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
INFO: > cmd='/venv/bin/invoke docker_jupyter'
-----------------------------------------------------------------------------
This code is not in sync with the container:
code_version='1.4.3' != container_version='1.4.0'
-----------------------------------------------------------------------------
You need to:
- merge origin/master into your branch with `invoke git_merge_master`
- pull the latest container with `invoke docker_pull`
## docker_jupyter: 
Traceback (most recent call last):
  File "/venv/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/venv/lib/python3.8/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/venv/lib/python3.8/site-packages/invoke/program.py", line 569, in execute
    executor.execute(*self.tasks)
  File "/venv/lib/python3.8/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/venv/lib/python3.8/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/app/helpers/lib_tasks_docker.py", line 1379, in docker_jupyter
    git_repo_idx = hgit.get_project_dirname(only_index=True)
  File "/app/helpers/hgit.py", line 166, in get_project_dirname
    hdbg.dassert(
  File "/app/helpers/hdbg.py", line 159, in dassert
    _dfatal(txt, msg, *args, only_warning=only_warning)
  File "/app/helpers/hdbg.py", line 142, in _dfatal
    dfatal(dfatal_txt)
  File "/app/helpers/hdbg.py", line 71, in dfatal
    raise assertion_type(ret)
AssertionError: 
################################################################################
* Failed assertion *
cond=False
The last char `p` of the git dir `/app` is not a digit
################################################################################

17:41:45 - INFO  hcache.py clear_global_cache:292                       Before clear_global_cache: 'global mem' cache: path='/mnt/tmpfs/tmp.cache.mem', size=32.0 KB
17:41:46 - WARN  hcache.py clear_global_cache:293                       Resetting 'global mem' cache '/mnt/tmpfs/tmp.cache.mem'
17:41:46 - WARN  hcache.py clear_global_cache:303                       Destroying '/mnt/tmpfs/tmp.cache.mem' ...
17:41:46 - INFO  hcache.py clear_global_cache:319                       After clear_global_cache: 'global mem' cache: path='/mnt/tmpfs/tmp.cache.mem', size=nan
```

Any idea why this error ? Trying to investigate.

**Comment by gpsaggese** [comment]
All the `i docker_*` commands should be run outside the container and spawn automatically the container

**Comment by sonaalKant** [comment]
After setting everything up, I ran fast tests, and got this output. Can someone tell if this is the  expected output? or I might have missed something which I have to revisit and debug. 

```
================================================ 94 failed, 2128 passed, 207 skipped, 191 deselected, 2 xfailed, 14 errors, 75 rerun in 1273.75s (0:21:13) =================================================
19:58:26 @ 2023-07-21 03:49:33 - INFO  hcache.py clear_global_cache:292 Before clear_global_cache: 'global mem' cache: path='/mnt/tmpfs/tmp.cache.mem', size=28.0 KB
19:58:26 @ 2023-07-21 03:49:33 - WARN  hcache.py clear_global_cache:293 Resetting 'global mem' cache '/mnt/tmpfs/tmp.cache.mem'
19:58:26 @ 2023-07-21 03:49:33 - WARN  hcache.py clear_global_cache:303 Destroying '/mnt/tmpfs/tmp.cache.mem' ...
19:58:26 @ 2023-07-21 03:49:33 - INFO  hcache.py clear_global_cache:319 After clear_global_cache: 'global mem' cache: path='/mnt/tmpfs/tmp.cache.mem', size=nan
ERROR: 1

```

**Comment by gpsaggese** [comment]
In general, can you attach all the output as txt file so that we can tell you more?

In this case, `pytest` ran and some tests are failing (which is expected since we are still working on https://github.com/sorrentum/sorrentum/issues/283)

You can assume that the unit tests are fine and you can continue in the on-boarding. 

Good stuff.

**Comment by sonaalKant** [comment]
Hi, Can I now be assigned with the warmup issue. Also the hyperlink of morning email directs me to 404. I assume you wanted to use this https://github.com/sorrentum/sorrentum/blob/master/docs/General_rules_of_collaboration.md#morning-email

**Comment by samarth9008** [comment]
Assigned https://github.com/sorrentum/sorrentum/issues/443

**Comment by DanilYachmenev** [comment]
done, closing
