### ISSUE TITLE
Sorrentum Fast tests stops after a while

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#650]
https://github.com/sorrentum/sorrentum/actions/runs/7802785829?pr=649

Currently the fast tests stops in between 

The error is similar to what we faced on orange, related to no space left on device.

```
System.IO.IOException: No space left on device : '/home/runner/runners/2.312.0/_diag/Worker_20240206-171353-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.312.0/_diag/Worker_20240206-171353-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.312.0/_diag/Worker_20240206-171353-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)
```

No notifications are send to the group or on email related to this halt in execution.

FYI @gpsaggese  @dremdem @PomazkinG

**Comment by PomazkinG** [comment]
@samarth9008 I believe we need to merge the `setUp/tearDown` fix to sorrentum, i.e. use the fixture approach -- see https://github.com/cryptokaizen/cmamp/issues/6825

Ideally, we need to do an integration cmamp -> sorrentum. But merging little by little is also a viable approach

**Comment by samarth9008** [comment]
@sonniki 

Can you apply the same fix on the sorrentum as well?

**Comment by gpsaggese** [comment]
@PomazkinG let's put an integration on the agenda of the next meeting. If we pay the accumulated integration debt, it will become an easy operation.

**Comment by sonniki** [comment]
> @PomazkinG let's put an integration on the agenda of the next meeting. If we pay the accumulated integration debt, it will become an easy operation.

In light of this, should I still apply the fix manually, or the integration will be soon enough for the manual fix not to be needed?

**Comment by gpsaggese** [comment]
Let's wait for the integration.

It's ok for the break to be broken until this is done

**Comment by samarth9008** [comment]
Closing as resolved after integration
