### ISSUE TITLE
On-board Shengjie Xu

### ISSUE THREAD

**Issue by sonaalKant** [sorrentum/sorrentum#665]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#Important) 
  - [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.organize_your_work.how_to_guide.md)
  - [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/sorrentum.development.how_to_guide.md)
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.docker.how_to_guide.md) works
  - [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) run successfully
  - [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md)
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [x] Get assigned a warm-up issue
  - [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email)
  - [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)
  - [ ] If you are graduating soon and you would like to get a full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at [gp@sorrentum.org](mailto:gp@sorrentum.org)

FYI @gpsaggese @samarth9008

**Comment by jayhsu0627** [comment]
```Collecting PyYAML<6,>=3.10 (from docker-compose>=1.29.0->-r dev_scripts/client_setup/requirements.txt (line 4))
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/shengjiexu/src/venv/amp.client_venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/shengjiexu/src/venv/amp.client_venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/shengjiexu/src/venv/amp.client_venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/private/var/folders/v0/tbqkhzgx1132y1x64chm4yvw0000gn/T/pip-build-env-k1gdjdng/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[Process completed]

**Comment by samarth9008** [comment]
The useful link is unrelated. You need to install docker in your laptop to move forward. I think you can install docker without docker-desktop.

**Comment by jayhsu0627** [comment]
@samarth9008  I've installed the env of `source dev_scripts/client_setup/build.sh` by manually installed docker
```
brew install docker
brew link docker
brew install colima
```

However, a new `command not found: complete` issue pop-out by running `source dev_scripts/setenv_amp.sh`

```
# Configure env
which gh=/opt/homebrew/bin/gh
AM_AWS_PROFILE=am
AM_AWS_S3_BUCKET=alphamatic-data
AM_ECR_BASE_PATH=665840871993.dkr.ecr.us-east-1.amazonaws.com
CK_AWS_PROFILE=ck
CK_AWS_S3_BUCKET=cryptokaizen-data
TERM_PROGRAM_VERSION=453
i=invoke
ih='invoke --help'
il='invoke --list'
it='invoke traceback'
itpb='pbpaste | traceback_to_cfile.py -i - -o cfile'
run-help=man
which-command=whence
# Enable invoke autocompletion.
/Users/sheng***/src/sorrentum1/dev_scripts/invoke_completion.sh:33: command not found: complete
```
```
brew install bash_completion
brew install apm-bash-completion
```

After Google, I guess it's because I'm using a pure macos shell instead of zsh. So I try to install (zsh)[https://sourabhbajaj.com/mac-setup/iTerm/zsh.html]

it works now

```
gwt='git worktree'
gwta='git worktree add'
gwtls='git worktree list'
gwtmv='git worktree move'
gwtrm='git worktree remove'
history=omz_history
i=invoke
ih='invoke --help'
il='invoke --list'
it='invoke traceback'
itpb='pbpaste | traceback_to_cfile.py -i - -o cfile'
l='ls -lah'
la='ls -lAh'
ll='ls -lh'
ls='ls -G'
lsa='ls -lah'
md='mkdir -p'
rd=rmdir
run-help=man
which-command=whence
# Enable invoke autocompletion.
==> SUCCESS <==
```

**Comment by gpsaggese** [comment]
Good job @jayhsu0627 investigating.

1) I use `bash` on my M2 mac and things are fine with `complete`
```
saggese@gpmac.local ==> RC: 1 <== venv:(amp.client_venv) branch:'master' ~/src/sorrentum1
> echo $SHELL
/bin/bash

saggese@gpmac.local venv:(amp.client_venv) branch:'master' ~/src/sorrentum1
> source dev_scripts/invoke_completion.sh
# Enable invoke autocompletion.
```

2) @samarth9008 can we update the doc clarifying that one needs Docker desktop of the GUI-less one
```
brew install docker
brew link docker
brew install colima
```

**Comment by jayhsu0627** [comment]
I try to verify my docker installation by running `i docker_jupyter` from [old_quick_start](https://github.com/sorrentum/sorrentum/blob/ecf0a5efc7c5cabd5a7d36be258ebb3851c415dc/docs/Quick_start_for_developing.md)

```(amp.client_venv) ➜  sorrentum1 git:(master) ✗ i docker_jupyter

INFO: > cmd='/Users/shengjiexu/src/venv/amp.client_venv/bin/invoke docker_jupyter'
## docker_jupyter: 
22:05:55 - INFO  lib_tasks_docker.py docker_jupyter:1449                Assigned port is 5011
22:05:55 - WARN  <string> _raise_invalid_host:90                        Don't recognize host: host_os_name=Darwin, am_host_os_name=None
22:05:55 - INFO  lib_tasks_docker.py _docker_cmd:1306                   Pulling the latest version of Docker
## docker_pull: 
## docker_login: 
## _docker_login_ecr: 
  ... 
  ... The config profile (ck) could not be found
22:05:55 - INFO  lib_tasks_docker.py _docker_pull:227                   image='623860924167.dkr.ecr.eu-north-1.amazonaws.com/cmamp:dev'
docker pull 623860924167.dkr.ecr.eu-north-1.amazonaws.com/cmamp:dev
Error response from daemon: Head "https://623860924167.dkr.ecr.eu-north-1.amazonaws.com/v2/cmamp/manifests/dev": no basic auth credentials
```

```
(amp.client_venv) ➜  sorrentum1 git:(master) ✗ i docker_pull_dev_tools

INFO: > cmd='/Users/shengjiexu/src/venv/amp.client_venv/bin/invoke docker_pull_dev_tools'
## docker_pull_dev_tools: 
## docker_login: 
## _docker_login_ecr: 
  ... 
  ... The config profile (ck) could not be found
22:08:09 - INFO  lib_tasks_docker.py _docker_pull:227                   image='623860924167.dkr.ecr.eu-north-1.amazonaws.com/dev_tools:prod'
docker pull 623860924167.dkr.ecr.eu-north-1.amazonaws.com/dev_tools:prod
Error response from daemon: Head "https://623860924167.dkr.ecr.eu-north-1.amazonaws.com/v2/dev_tools/manifests/prod": no basic auth credentials
```
But I got a bad AWS credentials error, I know I didn't setup an AWS id. Maybe it's the same as this warning?

```
WARNING: The AM_AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
```

**Comment by samarth9008** [comment]
Are you able to do `i docker_pull`?

**Comment by gpsaggese** [comment]
1) I see `rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2` that makes me think that for some reason you might be using the x86 image + emulator and not the Apple Silicon one (which of course it's slower since it goes through the translation layer).

@samarth9008 we should have a check / warning about this. I'll file a bug.

2) The error is because you don't have docker-in-docker enabled. This is an old way of doing things that we don't really use anymore.

In repo_config.py, you can set check_repo = False

```
198     # dind is supported on both Mac and GH Actions.
199     check_repo = os.environ.get("AM_REPO_CONFIG_CHECK", "True") != "False"
200     if check_repo:
201         if hserver.is_cmamp_prod():
202             assert not has_dind, "Not expected privileged mode"
```

I'll file another bug to make this check optional.

**Comment by gpsaggese** [comment]
2) The error is because you don't have docker-in-docker enabled. This is an old way of doing things that we don't really use anymore.

In repo_config.py, you can set check_repo = False

```
198     # dind is supported on both Mac and GH Actions.
199     check_repo = os.environ.get("AM_REPO_CONFIG_CHECK", "True") != "False"
200     if check_repo:
201         if hserver.is_cmamp_prod():
202             assert not has_dind, "Not expected privileged mode"
```

I'll file another bug to make this check optional.

**Comment by samarth9008** [comment]
Updated link for setup - https://github.com/sorrentum/sorrentum/blob/master/docs/onboarding/sorrentum.set_up_development_environment.how_to_guide.md

**Comment by jayhsu0627** [comment]
> 2. The error is because you don't have docker-in-docker enabled. This is an old way of doing things that we don't really use anymore.
> 
> In repo_config.py, you can set check_repo = False
> 
> ```
> 198     # dind is supported on both Mac and GH Actions.
> 199     check_repo = os.environ.get("AM_REPO_CONFIG_CHECK", "True") != "False"
> 200     if check_repo:
> 201         if hserver.is_cmamp_prod():
> 202             assert not has_dind, "Not expected privileged mode"
> ```
> 
> I'll file another bug to make this check optional.

After ignoring the `dind` check by setting `check_repo = False`, I can successfully get ` i docker_bash` and ` i docker_bash` running.

```
...
# Env vars:
  AM_AWS_ACCESS_KEY_ID=undef
  AM_AWS_DEFAULT_REGION=undef
  AM_AWS_PROFILE='am'
  AM_AWS_S3_BUCKET='alphamatic-data'
  AM_AWS_SECRET_ACCESS_KEY=undef
  AM_ECR_BASE_PATH='665840871993.dkr.ecr.us-east-1.amazonaws.com'
  AM_ENABLE_DIND='0'
  AM_FORCE_TEST_FAIL=''
  AM_HOST_NAME='sjxu'
  AM_HOST_OS_NAME='Darwin'
  AM_HOST_USER_NAME='username'
  AM_HOST_VERSION='23.3.0'
  AM_REPO_CONFIG_CHECK='True'
  AM_REPO_CONFIG_PATH=''
  AM_TELEGRAM_TOKEN=empty
  CI=''
  CK_AWS_ACCESS_KEY_ID=empty
  CK_AWS_DEFAULT_REGION=''
  CK_AWS_S3_BUCKET='cryptokaizen-data'
  CK_AWS_SECRET_ACCESS_KEY=empty
  CK_ECR_BASE_PATH='sorrentum'
  GH_ACTION_ACCESS_TOKEN=empty

22:06:26 - INFO  hcache.py clear_global_cache:294                       Before clear_global_cache: 'global mem' cache: path='/mnt/tmpfs/tmp.cache.mem', size=36.0 KB
22:06:26 - WARN  hcache.py clear_global_cache:295                       Resetting 'global mem' cache '/mnt/tmpfs/tmp.cache.mem'
22:06:26 - WARN  hcache.py clear_global_cache:305                       Destroying '/mnt/tmpfs/tmp.cache.mem' ...
22:06:26 - INFO  hcache.py clear_global_cache:321                       After clear_global_cache: 'global mem' cache: path='/mnt/tmpfs/tmp.cache.mem', size=nan
user_501@3bab0cb655bd:/app$   
```
```
(amp.client_venv) ➜  sorrentum1 git:(master) ✗ i docker_jupyter 5080
INFO: > cmd='/Users/username/src/venv/amp.client_venv/bin/invoke docker_jupyter 5080'
No idea what '5080' is!
(amp.client_venv) ➜  sorrentum1 git:(master) ✗ i docker_jupyter -p 5080
INFO: > cmd='/Users/username/src/venv/amp.client_venv/bin/invoke docker_jupyter -p 5080'
## docker_jupyter: 
22:10:48 - INFO  lib_tasks_docker.py docker_jupyter:1449                Assigned port is 5080
22:10:48 - WARN  <string> _raise_invalid_host:90                        Don't recognize host: host_os_name=Darwin, am_host_os_name=None
22:10:48 - INFO  lib_tasks_docker.py _docker_cmd:1306                   Pulling the latest version of Docker
## docker_pull: 
## docker_login: 
## _docker_login_ecr: 
  ... 
  ... The config profile (ck) could not be found
22:10:49 - INFO  lib_tasks_docker.py _docker_pull:227                   image='sorrentum/cmamp:dev'
docker pull sorrentum/cmamp:dev
dev: Pulling from sorrentum/cmamp
Digest: sha256:bf774bd028a92dbff5b0efafc505a7e40c88419c70447b3f815f9ee53ac72473
Status: Image is up to date for sorrentum/cmamp:dev
docker.io/sorrentum/cmamp:dev
IMAGE=sorrentum/cmamp:dev \
PORT=5080 \
        docker-compose \
        --file /Users/username/src/sorrentum1/devops/compose/docker-compose.yml \
        --env-file devops/env/default.env \
        run \
        --rm \
        --name username.cmamp.jupyter_server.sorrentum1.20240226_221048 \
        --user $(id -u):$(id -g) \
        --service-ports \
        jupyter_server 
WARNING: The AM_AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
WARNING: The AM_AWS_DEFAULT_REGION variable is not set. Defaulting to a blank string.
WARNING: The AM_AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
WARNING: The AM_FORCE_TEST_FAIL variable is not set. Defaulting to a blank string.
WARNING: The AM_TELEGRAM_TOKEN variable is not set. Defaulting to a blank string.
WARNING: The CK_AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
WARNING: The CK_AWS_DEFAULT_REGION variable is not set. Defaulting to a blank string.
WARNING: The CK_AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
WARNING: The CK_TELEGRAM_TOKEN variable is not set. Defaulting to a blank string.
Creating compose_jupyter_server_run ... done
##> devops/docker_run/entrypoint.sh
UID=501
GID=20
# Activate environment
##> devops/docker_run/setenv.sh
# Set PATH
PATH=/app/dev_scripts/testing:/app/dev_scripts/notebooks:/app/dev_scripts/install:/app/dev_scripts/infra:/app/dev_scripts/git:/app/dev_scripts/documentation:/app/dev_scripts/aws:/app/dev_scripts:/app:.:/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# Set PYTHONPATH
PYTHONPATH=/app:
# Configure env
git --version: git version 2.25.1
/app
WARNING: AWS credential check failed: can't find /home/.aws/credentials file.
WARNING: AWS credential check failed: can't find /home/.aws/config file.
# Check AWS authentication setup
rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
 devops/docker_run/entrypoint.sh: line 109:    21 Trace/breakpoint trap   aws configure --profile am list
AM_CONTAINER_VERSION='1.12.0'
which python: /venv/bin/python
python -V: Python 3.9.5
helpers: <module 'helpers' from '/app/helpers/__init__.py'>
PATH=/app/dev_scripts/testing:/app/dev_scripts/notebooks:/app/dev_scripts/install:/app/dev_scripts/infra:/app/dev_scripts/git:/app/dev_scripts/documentation:/app/dev_scripts/aws:/app/dev_scripts:/app:.:/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PYTHONPATH=/app:
entrypoint.sh: 'devops/docker_run/run_jupyter_server.sh'
WARNING: Skip checking since AM_REPO_CONFIG_CHECK='True'
INFO: > cmd='/venv/bin/invoke print_env'
22:11:01 - WARN  <string> _raise_invalid_host:90                        Don't recognize host: host_os_name=Linux, am_host_os_name=Darwin
WARNING: Skip checking since AM_REPO_CONFIG_CHECK='True'
(CVXPY) Feb 27 03:11:01 AM: Encountered unexpected exception importing solver GLPK:
ImportError("cannot import name 'glpk' from 'cvxopt' (/venv/lib/python3.9/site-packages/cvxopt/__init__.py)")
(CVXPY) Feb 27 03:11:01 AM: Encountered unexpected exception importing solver GLPK_MI:
ImportError("cannot import name 'glpk' from 'cvxopt' (/venv/lib/python3.9/site-packages/cvxopt/__init__.py)")
# Repo config:
  # repo_config.config
    enable_privileged_mode='False'
    get_docker_base_image_name='cmamp'
    get_docker_shared_group=''
    get_docker_user=''
    get_host_name='github.com'
    get_html_dir_to_url_mapping='{'s3://cryptokaizen-html': 'http://172.30.2.44'}'
    get_invalid_words='[]'
    get_name='//sorr'
    get_repo_map='{'sorr': 'sorrentum/sorrentum'}'
    get_shared_data_dirs='None'
    has_dind_support='False'
    has_docker_sudo='True'
    is_CK_S3_available='True'
    run_docker_as_root='False'
    skip_submodules_test='False'
    use_docker_db_container_name_to_connect='False'
    use_docker_network_mode_host='False'
    use_docker_sibling_containers='False'
    # hserver.config
      is_AM_S3_available()='True'
      is_dev4()='False'
      is_dev_ck()='False'
      is_inside_ci()='False'
      is_inside_docker()='True'
      is_mac(version='Catalina')='False'
      is_mac(version='Monterey')='False'
      is_mac(version='Ventura')='False'
# System signature:
  # Git
    branch_name='master'
    hash='95fb77aba'
    # Last commits:
      * 95fb77aba Samarth KaPatel update (#675)                                                     (    3 days ago) Fri Feb 23 16:42:39 2024  (HEAD -> master, origin/master, origin/HEAD)
      * d39076822 Vlad     fix from cmamp (#674)                                             (    4 days ago) Fri Feb 23 14:53:28 2024           
      * c3e351cbd GP Saggese AmpTask1786_Integrate_20240219_5 (#669)                           (    5 days ago) Wed Feb 21 22:27:11 2024           
  # Machine info
    system=Linux
    node name=a6171d0581e3
    release=6.6.12-linuxkit
    version=#1 SMP Thu Feb  8 06:36:34 UTC 2024
    machine=aarch64
    processor=aarch64
    cpu count=8
    cpu freq=None
    memory=svmem(total=8222334976, available=7053840384, percent=14.2, used=958861312, free=1380122624, active=1268436992, inactive=5147893760, buffers=79269888, cached=5804081152, shared=1527808, slab=303693824)
    disk usage=sdiskusage(total=62671097856, used=14573363200, free=44881018880, percent=24.5)
  # Packages
    python: 3.9.5
    cvxopt: 1.3.2
    cvxpy: 1.4.2
    gluonnlp: ?
    gluonts: ?
    joblib: 1.3.2
    mxnet: ?
    numpy: 1.26.0
    pandas: 2.1.1
    pyarrow: 14.0.2
    scipy: 1.11.3
    seaborn: 0.13.0
    sklearn: 1.3.1
    statsmodels: 0.14.0
# Env vars:
  AM_AWS_ACCESS_KEY_ID=undef
  AM_AWS_DEFAULT_REGION=undef
  AM_AWS_PROFILE='am'
  AM_AWS_S3_BUCKET='alphamatic-data'
  AM_AWS_SECRET_ACCESS_KEY=undef
  AM_ECR_BASE_PATH='665840871993.dkr.ecr.us-east-1.amazonaws.com'
  AM_ENABLE_DIND='0'
  AM_FORCE_TEST_FAIL=''
  AM_HOST_NAME='sjxu'
  AM_HOST_OS_NAME='Darwin'
  AM_HOST_USER_NAME='username'
  AM_HOST_VERSION='23.3.0'
  AM_REPO_CONFIG_CHECK='True'
  AM_REPO_CONFIG_PATH=''
  AM_TELEGRAM_TOKEN=empty
  CI=''
  CK_AWS_ACCESS_KEY_ID=empty
  CK_AWS_DEFAULT_REGION=''
  CK_AWS_S3_BUCKET='cryptokaizen-data'
  CK_AWS_SECRET_ACCESS_KEY=empty
  CK_ECR_BASE_PATH='sorrentum'
  GH_ACTION_ACCESS_TOKEN=empty

22:11:01 - INFO  hcache.py clear_global_cache:294                       Before clear_global_cache: 'global mem' cache: path='/mnt/tmpfs/tmp.cache.mem', size=36.0 KB
22:11:01 - WARN  hcache.py clear_global_cache:295                       Resetting 'global mem' cache '/mnt/tmpfs/tmp.cache.mem'
22:11:01 - WARN  hcache.py clear_global_cache:305                       Destroying '/mnt/tmpfs/tmp.cache.mem' ...
22:11:01 - INFO  hcache.py clear_global_cache:321                       After clear_global_cache: 'global mem' cache: path='/mnt/tmpfs/tmp.cache.mem', size=nan
##> devops/docker_run/run_jupyter_server.sh
> cmd=jupyter notebook --ip=* --port=5080 --allow-root --NotebookApp.token=''
[W 03:11:02.071 NotebookApp] Config option `default_jupytext_formats` not recognized by `LargeFileManager`.
[W 03:11:02.071 NotebookApp] Config option `preferred_jupytext_formats_save` not recognized by `LargeFileManager`.
[W 03:11:02.071 NotebookApp] Config option `outdated_text_notebook_margin` not recognized by `LargeFileManager`.  Did you mean `untitled_notebook`?
[I 03:11:02.089 NotebookApp] Writing notebook server cookie secret to /home/.local/share/jupyter/runtime/notebook_cookie_secret
[I 03:11:02.090 NotebookApp] Authentication of /metrics is OFF, since other authentication is disabled.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                       
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[W 03:11:02.434 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 03:11:02.434 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 03:11:02.437 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.6.3
[I 03:11:02.486 NotebookApp] [Jupytext Server Extension] Deriving a JupytextContentsManager from LargeFileManager
[I 03:11:02.489 NotebookApp] Serving notebooks from local directory: /app
[I 03:11:02.489 NotebookApp] Jupyter Notebook 6.5.6 is running at:
[I 03:11:02.489 NotebookApp] http://a6171d0581e3:5080/
[I 03:11:02.489 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 03:11:02.492 NotebookApp] No web browser found: could not locate runnable browser.
```

**Comment by sonaalKant** [comment]
I have assigned you the warm up issue https://github.com/sorrentum/sorrentum/issues/695

**Comment by gpsaggese** [comment]
1) The docker image is multi-arch so it should pull automatically the right one. In fact I don't see the warning from Rosetta about running x86 images

2) If you close the container, it should release the port. Otherwise you can force kill the container
